name: news_app_clean
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_lints: ^5.0.0
  #state management
  flutter_bloc: ^9.1.0

  #comparing dart objects
  equatable: ^2.0.7

  #service locator
  get_it: ^8.0.3

  #departmant
  intl: ^0.20.2

  #database
  floor: ^1.5.0

  #make request to api
  retrofit: ^4.4.2

  #hooks
  flutter_hooks: ^0.21.2

  #cached_network_image
  cached_network_image: ^3.2.0

  dio:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  retrofit_generator:
  floor_generator:
  build_runner:



flutter:
  uses-material-design: true
